apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
networking:
    dnsDomain: cluster.local
    podSubnet: 10.244.0.0/16
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls:
- "net.ipv4.ip_forward"
